services:
  ragnabot:
    restart: unless-stopped
    build: ./src
    volumes:
      - ./db:/app/db
    develop:
      watch:
        - action: rebuild
          path: ./src
          ignore:
            - bin/
            - obj/
            - db/
    environment:
      DOTNET_DiscordBotToken: ${DISCORD_BOT_TOKEN}
      DOTNET_ArcadiaApiToken: ${ARCADIA_API_TOKEN}
      DOTNET_ArcadiaBaseUrl: ${ARCADIA_BASE_URL}
      DOTNET_InfluxDbUrl: http://influxdb:8086
      DOTNET_InfluxDbToken: ${INFLUXDB_TOKEN}

  influxdb:
    restart: unless-stopped
    image: influxdb:2
    pull_policy: always
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_INIT_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_INIT_PASSWORD}
      DOCKER_INFLUXDB_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
    ports:
      - 8086:8086
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2

volumes:
  influxdb-data:
  influxdb-config:
